Upgrade to node18 and ng15 (#768)
* initiate node 18 upgrade

* Bumping chart version/ fixing aliases

* initiate node 18 upgrade

* upgrade to ng 12

* wounded upgrade to Angular-13

* upgrade to ng 14

* upgrade yarn to 3.6.1

* wounded upgrade to ng-15

* fix security scan

* temp disable dependency audits

* ignore smoke test

* ignore tests tagged as @Ignore

* fix broken ng-15

* ignore tests tagged as @Ignore

* fix broken ng-15

* re-enable smoke tests

* use latest xui common lib and node lib

* use prerelease of common lib and node lib

* use prerelease of common lib and non-upgraded node lib

* fix "Cannot resolve type entity i68.RpxTranslationModule to symbol"

* fix failing tests

* use upgraded rpx translate

* cleanup

* use latest RC of upgraded toolkit

* use yarn 3.5.0 with latest pipeline lib

* Revert "use yarn 3.5.0 with latest pipeline lib"

This reverts commit 03453b43fd95a56bdc1b80f6e7b940a094719bac.

* upgrade to yarn@4.0.0-rc.50

* update known issues

* test disable test:api

* refactor as protractor support removed from ng-15

* fix issue of mocha hanging at end

* refactor: Code tidy replace UntypedForm with Form

* Updated pa11y to 6.2.3

* Display test payload

* Code tidy

* package.json lock updated pa11y to 6.2.3

* fix issue displayed in console when running yarn install

* Fix error - cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.

* Cody tide

* Update yarn.lock

* removed chromedriver previously added from package.json

* package.json updated

* Upadte cucumber in package.json

* update require('cucumber') to require('@cucumber/cucumber')

update require('cucumber') to require('@cucumber/cucumber')

Code tidy

Code tidy

update cucumber-pretty version

remove node_modules/cucumber-pretty from test

Code tidy

yarn.lock update

test:funcion updated in package.json

Troubleshoot bug

Code tidy

Code tidy

Added @cucumber/cucumber to package.json

Testing

Testing

* Testing

* Updated test:ngIntegration script

* refactor: EXUI-846 - using the current stable version of yarn 3.6.3. Resolve issue with yarn audit

* refactor: Use current jenkins infraascture settings

* refactor: revert back to 4.0.0-rc.50

* EXUI-852: NullInjectorError: R3InjectorError(ut)[i -> i -> i]:
NullInjectorError: No provider for i!

* refactor: EXUI-846 - using the current stable version of yarn 3.6.3. to resolution is with yarn audit

* Code tidy. Place the property stylePreprocessorOptions in the correct position in angular.json

* yarn-audit-know-issue file updated

---------

Co-authored-by: hmcts-jenkins-j-to-z <61242337+hmcts-jenkins-j-to-z[bot]@users.noreply.github.com>
Co-authored-by: olusegun odunukan <olusegun.odunukan@hmcts.net>
Co-authored-by: Olu <142989683+olusegz07@users.noreply.github.com>
Co-authored-by: Munish Sharma <Munish.Sharma@HMCTS.NET>